/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "convert.h"


void
convert_1(char *host,int n)
{
	CLIENT *clnt;
	int  *result_1;
	int  convert_hex_1_arg=n;
	int  *result_2;
	int  convert_oct_1_arg=n;

#ifndef	DEBUG
	clnt = clnt_create (host, CONVERT, CONVERT_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = convert_hex_1(&convert_hex_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else 
		printf("Equivalent Hexadecimal Number %x\n",*result_1);
	
	result_2 = convert_oct_1(&convert_oct_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else 
		printf("Equivalent octal Number %d\n",*result_2);
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	convert_1 (host,atoi(argv[2]));
	exit (0);
}
